# Generated by Django 5.1.6 on 2025-03-08 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_order_order_no_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_no',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
