# Generated by Django 5.1.6 on 2025-03-29 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0008_menuitemsize'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='price',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='quantity',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='default_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_items', to='staff.menuitemsize'),
        ),
    ]
