# Generated by Django 5.1.6 on 2025-03-29 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0009_remove_menuitem_price_remove_menuitem_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='default_size',
        ),
        migrations.AddField(
            model_name='menuitemsize',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
