# Generated by Django 5.1.6 on 2025-04-03 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0010_remove_menuitem_default_size_menuitemsize_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='template',
            field=models.CharField(choices=[('starter', 'Starter'), ('modern', 'Modern'), ('premium', 'Premium'), ('pictorial', 'Pictorial')], default='starter', max_length=10),
        ),
    ]
