# Generated by Django 5.0.4 on 2025-06-30 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0012_auto_20250701_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='image_url',
            field=models.CharField(blank=True, help_text='Stores the URL/path of the placeholder or generated image.', max_length=255),
        ),
    ]
