# Generated by Django 5.0.4 on 2025-06-30 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0013_menuitem_image_url'),
    ]

    operations = [
    ]
