# Generated by Django 5.0.4 on 2025-06-30 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0014_auto_20250701_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='menucategory',
            name='image_url',
            field=models.CharField(blank=True, help_text='Stores the URL/path of the placeholder or generated image.', max_length=255),
        ),
    ]
