# Generated by Django 5.1.6 on 2025-07-06 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0016_remove_owner_email_remove_owner_name_owner_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('preparing', 'Preparing'), ('ready', 'Ready to Serve'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
